/**
 * Generated by orval v6.12.0 🍺
 * Do not edit manually.
 * Coworker API
 * OpenAPI spec version: 0.0.1
 */

export interface ApiUserResponse {
  email: string
  first_name?: string
  id?: string
  last_name?: string
}
